### ISSUE TITLE
Find better icon

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#101]
Per @DavidNesbitt .. let's find a better icon with more ambiguous character.

**Comment by jakub-bao** [comment]
"something very neutral"

**Comment by benguaraldi** [comment]
Maybe it makes sense to just use the PEPFAR logo?

**Comment by DavidNesbitt** [comment]
We use the PEPFAR logo for the DATIM Support App icon already. 

![image](https://user-images.githubusercontent.com/23367121/55158370-1c371800-5135-11e9-90e1-3c7e7982484e.png)

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/55340591-026a3d80-5473-11e9-9dc1-8d7add1520e8.png)

@DavidNesbitt @benguaraldi How about this icon?

**Comment by DavidNesbitt** [comment]
Hey @jakub-bao - I like the colors and the multi-person layout a lot!!  To represent more broadly our user community through the app icon, can we tweak it a little further? Maybe have the three "people icons" be slightly different from each other - similar to the icon below (but incorporate your color scheme)?

![image](https://user-images.githubusercontent.com/23367121/55490900-8c94dc00-5602-11e9-841c-0288796f568f.png)

**Comment by jakub-bao** [comment]
sure, i'll look for something like this.

**Comment by jakub-bao** [comment]
Will re-brainstorm later together.

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/56058309-07f73b80-5d2f-11e9-8ec3-a1eb459fcecf.png)

**Comment by jakub-bao** [comment]
@hardingt @hkim224 What do you guys think about this logo for the user management app?

@benguaraldi Can you tag Frode? I can't find him :(

**Comment by DavidNesbitt** [comment]
This is my opinion (so take it/leave it) but I think it's too much like the DATIM support icon. If a user accidentally clicks the DATIM User Support icon (redirects to external page), when they meant to click the user admin icon (internal DATIM app), it could take a while to redirect themselves back into DATIM.  That clicking/re-clicking user behavior, in my opinion, detracts from overall user satisfaction.

**Comment by hardingt** [comment]
@DavidNesbitt agreed. I am going to ask Frode to take a look tomorrow

**Comment by jakub-bao** [comment]
Got it.

**Comment by jakub-bao** [comment]
Free icons here:
https://www.iconfinder.com/search/?q=users
https://thenounproject.com/search/?q=users

Some alternatives:
![image](https://user-images.githubusercontent.com/47790868/58191374-65ff3300-7c8c-11e9-89bf-8338b237b92c.png)

![image](https://user-images.githubusercontent.com/47790868/58191433-8a5b0f80-7c8c-11e9-9aa3-3005ea8abab0.png)

![image](https://user-images.githubusercontent.com/47790868/58191519-b7a7bd80-7c8c-11e9-915e-545175bfeb9b.png)

**Comment by jakub-bao** [comment]
@benguaraldi @hkim224 @hardingt do u like any of the above?

**Comment by jakub-bao** [comment]
Per @hkim224 

![image](https://user-images.githubusercontent.com/47790868/58198055-93071200-7c9b-11e9-9466-19dd3500dc0e.png)

Let's use some icon which associates "user" & "configuration" together.

**Comment by jakub-bao** [comment]
@frodendahl

**Comment by hardingt** [comment]
@hkim224 and @jakub-bao I'm not sure the process for procuring an icon, in the meantime lets use the existing one until we can track that down.

@jakub-bao can you link me to that image up there so I can see about getting it purchased?
