### ISSUE TITLE
FAST vs ADVANCED search

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#105]
Majority of the search queries are slow...

However, the built-in Users app is not that bad.

Figure out how we can optimize queries

**Comment by jakub-bao** [comment]
Query types:

1. Filter Active users
2. Search by Name
3. Search by Email
4. Search by Username
5. Search by User Type
6. Search by Operating Unit
7. Search by User Groups

**Comment by benguaraldi** [comment]
This seems like something to do after the MVP—does that sound right to you, @jakub-bao?

**Comment by jakub-bao** [comment]
Got it.
Since I already started (1hr) let me just wrap up a bit (another 1hr) and then jump on other ticket.

However, note from our call. The new DHIS2 app is using in-built user-query feature.
We should do the same:

https://dev-jakub.datim.org/api/29/users?query=jakub&fields=id%2CfirstName%2Csurname%2CdisplayName%2Cemail%2C%0A%20%20organisationUnits%5Bname%2CdisplayName%2Cid%2Clevel%5D%2C%0A%20%20userCredentials%5Busername%2Cdisabled%2CuserRoles%5Bid%2Cname%2CdisplayName%5D%5D%2C%0A%20%20userGroups%5Bname%2CdisplayName%2Cid%5D&canManage=true&paging=true&page=0

**Comment by jakub-bao** [comment]
This is the documentation:

https://docs.dhis2.org/2.31/en/developer/html/webapi_users.html

**Comment by jakub-bao** [comment]
@benguaraldi & @DavidNesbitt I'm done with this for now.

However, let's talk about it sometime. I think I'd need only 1 day of work to replace the queries in the app.

Search by Name, Username, Email would go from 10sec to 1sec only.

**Comment by benguaraldi** [comment]
If it's one day, I'm cool with it, even though it isn't MVP. @DavidNesbitt, do you agree?

**Comment by jakub-bao** [comment]
@benguaraldi 
Thanks I'll do it sometime next week.
I think the app will be much better!

**Comment by jakub-bao** [comment]
This will probably need a bit UI change:

1) Google like search with only one search input (good for 90% used cases)

2) Option for advanced search which lets u specify all categories like right now (10% of advanced user queries)

The option #1 is using the DHIS2 built-in User Query feature which is super fast and I think it's really good. It searches: Name, Username & Email at the same time.

In my option the option #2 will be still good for some users but option #1 should do majority of the job.


Notes for me:

Right now the process is:

list.js:98 calls getUserListing()

list.js:52 calls apiFetchUsers(params) [be sure params.query='ben']

users.js:45 does the actual low-level call to D2

**Comment by jakub-bao** [comment]
Make use of DHIS2 native version of searching.
Searching in username, name, email in one single query.
That will make searching for users faster.

Then current searching dialog will be accessible as ADVANCED search.

**Comment by benguaraldi** [comment]
Closing.
