### ISSUE TITLE
Enforce invitation rights logic

### ISSUE THREAD

**Issue by Awnage** [pepfar-datim/datim-user-management-ng#11]
- IA can only invite to their IA
- MOH can only invite to their MOH
- Global can only invite to Global (disable User Manager checkbox)
- Partners can only invite to the same Partner
- Agencies can only invite to the same Agency or one of its Partners

**Comment by Awnage** [comment]
This needs to be tested by @hardingt

**Comment by hardingt** [comment]
@Awnage Huzzah! Testing tomorrow.

**Comment by jakub-bao** [comment]
Please correct the rules. Thanx.

**Comment by DavidNesbitt** [comment]
Thanks @jakub-bao 

I think the following correction should be made to the first IA rule/bullet listed in the first comment above:

- ~IA can only invite to their IA~

- **Inter-Agency user administrators can only invite MoH, MoH UA, Partner, Partner UA, Agency, Agency UA, Inter-Agency, and Inter-Agency UA for their OUs. They can not invite Global users.**

Overall, the logic for invitation enforcement should be that user administrators should only have the options to invite users they are actually allowed/supposed to invite to DATIM.
