### ISSUE TITLE
Invite page: Check roles for user manager

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#114]
I'm not sure if this is correct:

**User Type - Agency - HHS**

![image](https://user-images.githubusercontent.com/47790868/55490253-75a1ba00-5601-11e9-85a2-c6e1ee6ecc9a.png)

![image](https://user-images.githubusercontent.com/47790868/55490291-894d2080-5601-11e9-8fec-e2e104fe1cd9.png)

**Comment by jakub-bao** [comment]
Old app for reference:

![image](https://user-images.githubusercontent.com/47790868/55490336-9ff37780-5601-11e9-85ed-fd97c3e543ad.png)

**Comment by benguaraldi** [comment]
@hardingt, any thoughts?

**Comment by hardingt** [comment]
@benguaraldi this might have been a work around to allow Agency user admins to invite Partner users, without Data entry, they can't give that group to others. @hkim224 and @DavidNesbitt how often anymore do agency users create Partner accounts?

@jakub-bao you can confirm if the Agency user is created with those groups by making it with the angular app and checking the invited user's roles and groups.

**Comment by jakub-bao** [comment]
@hardingt Sure, will test that.

**Comment by hkim224** [comment]
Agency users invite and edit partner users quite a bit - this should be maintained as is into the REACT app.

**Comment by hardingt** [comment]
@hkim224 Noted

@jakub-bao best check to see if new Agency User Admins are being created correctly, just out of curiosity, and then make sure Agency User Admins can enter data to both MER and MER DOD.

**Comment by hkim224** [comment]
Invited an agency user manager in Triage. That user did NOT get Data Entry PRIME or Data Entry PRIME DOD (note that it is called PRIME in the user groups):

![image](https://user-images.githubusercontent.com/23666620/55648404-3bc1e680-57ae-11e9-9b05-2b2fdfc74557.png)

**Comment by hardingt** [comment]
@hkim224 can you then log in as that user and create a partner?

**Comment by jakub-bao** [comment]
conclusion => remove message when inviting Agency user

will check also for Partner, Inter-Agency, MOH

**Comment by hardingt** [comment]
@jakub-bao I'm not so sure yet. It could be an issue with the 2.29 angular app. I'm still not convinced the user @hkim224 created is enough to invite a partner user who can enter MER data, (but happy to be proven wrong of course)

**Comment by hkim224** [comment]
@hardingt I was able to invite a partner user with the agency account. The agency account did not have any of the data entry permissions. is this perhaps because it is a group and not a role that confers those permissions now?

**Comment by hardingt** [comment]
@hkim224 that is possible. As long as it works I'm happy with @jakub-bao 's synopsis

**Comment by jakub-bao** [comment]
Removed the msg. It was misleading. Thanx @hkim224 & @hardingt
