### ISSUE TITLE
Can edit roles for User Manager - However, old app wouldn't let me

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#115]
Hi, I found another discrepancy to the old app.

I am **Agency** user looking on **Used Admin** user:

![image](https://user-images.githubusercontent.com/47790868/55499504-29ac4080-5614-11e9-998c-d70cfa4e526c.png)

It seems like I can edit roles for user admin. However, the old app wouldn't let me do that.
In old app, **User Admin** should have access to data streams.

Which way should we go?

**Comment by jakub-bao** [comment]
Old app for reference: 

![image](https://user-images.githubusercontent.com/47790868/55499372-d803b600-5613-11e9-90c1-b871cfbe005c.png)

**Comment by jakub-bao** [comment]
In other words. Should we blur out all the checkboxes and make sure the highest privileges are selected once user is user manager?

**Comment by benguaraldi** [comment]
Good catch, @jakub-bao! I'm pretty sure the angular app's behavior is correct on this one.

@DavidNesbitt, @hardingt, any thoughts?

**Comment by hardingt** [comment]
@jakub-bao :

@benguaraldi is correct here. User Admins need every available stream and authority to be able to grant those to future users. Gray everything out and select the highest value.

**Comment by jakub-bao** [comment]
Per @DavidNesbitt ... Don't let user to adjust privileges for User Admin.
UA should always have everything.

**Comment by jakub-bao** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/47790868/55831896-3e8c4680-5ae2-11e9-92dd-f6c7a2eb561a.png)
