### ISSUE TITLE
Agencies should be able to invite people to their partners

### ISSUE THREAD

**Issue by Awnage** [pepfar-datim/datim-user-management-ng#12]
An agency user manager should be able to select `Partner` and pick one of that Agencies associated partners for that invitation.

**Comment by Awnage** [comment]
Is this right @hardingt ? The old app does not seem to allow this.

**Comment by hardingt** [comment]
@Awnage I was able to invite a partner account as an agency user in 2.27 with the old user admin app. Were you attempting this on the current user admin app in 2.29? I'm not sure that is ready for such a user invite yet.

![fingerscrossed](https://user-images.githubusercontent.com/11567315/43645251-527622b2-96ff-11e8-97db-60aae70bdcd2.gif)
