### ISSUE TITLE
Invite: List of countries is sometime empty

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#124]
This is often caught by our automated tests.
Invite page tests would fail 20% of the time because user can't see any countries in the menu.

This was soo hard to find! :)

Finally I was able to reproduce this issue by tracking it down and adding this code:

(lines 1-2 and 10+ are original code. to reproduce the issue i added lines 3-9)
core.js:77
```
    d2.models.organisationUnits
      .list(params)
      .then(ous=>{
        return new Promise((resolve, reject)=>{
          setTimeout(()=>{
            resolve(ous);
          },1000);
        });
      })
      .then(ous => {
        dispatch({ type: actions.SHOW_PROCESSING, status: true });
        dispatch({ type: actions.SET_COUNTRIES, data: ous.toArray() });
        // localStorage.setItem("countries", JSON.stringify(ous.toArray()));
        dispatch({ type: actions.HIDE_PROCESSING, status: false });
      })
```

The conclusion is obvious. There is a race condition.
It API works fast and REACT gets list of countries via API on time, then there is no issue.
However, around 20% cases REACT doesn't get the list of countries on time and page gets rendered and user cannot see any countries. User needs to refresh the page... :(

This is a real issue which would happen to me time to time but was near impossible to find and reproduce.
Finally we know which line of code it starts at.

I'll try to resolve the race condition to finally remove this!

**Comment by jakub-bao** [comment]
Note for myself:

To fix this we need to know this:

The loading of countries is initiated here:

`App.js:39`
```
    props.getCountries(props.d2);
```

**Comment by benguaraldi** [comment]
@jakub-bao Is it possible to wait five seconds or something and if the country list hasn't loaded just try to load it again?  It's fine if that isn't the way to go, just thought I'd suggest it.

**Comment by jakub-bao** [comment]
@benguaraldi Yes, that would be one option.. However, I am new to REDUX (the app is based on redux) and I wanted to understand how does the state/component lifecycle work and why it doesn't reflect the changes.

Finally fixed.

**Comment by jakub-bao** [comment]
Actually, this is the magic trick! :)

```
  componentDidUpdate(prevProps) {
    if (prevProps.core.countries !== this.props.core.countries) {
      this.resetFields();
    }
  }
```

Reset fields initializes the drop-down menus.
This was done before on a different place ` componentDidMount()` which was not appropriate (it's too time-sensitive and works on fast internet line only)

**Comment by jakub-bao** [comment]
I still see the error.
There must be one more race condition.

Unfortunately it makes my tests still failing...

**Comment by jakub-bao** [comment]
Another note:

The test are failing. The test agent can't see any countries.

However, it seems like REACT loaded them and has them.

![image](https://user-images.githubusercontent.com/47790868/56835932-985f7100-6843-11e9-848b-9e616a8e7b66.png)



Is it possible that the new component for Autocomplete is failing and swallowing the array of countries?

**Comment by jakub-bao** [comment]
Good news / bad news...

Good news that the time I've spent before really fixed some issues... The fact the list was missing due to slow internet is resolved! Yay!

Now the list is missing due to some bug in the `react-select` (autocomplete) library...

will just replace with this guy (or similar)

https://react-autosuggest.js.org/

**Comment by jakub-bao** [comment]
Had to revert the autocomplete library and re-write in plain Material-UI. But finally all tests are passing steadily!

**Comment by benguaraldi** [comment]
Yay!  Good job!
