### ISSUE TITLE
User list should be limited to only users the logged-in user has access to

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#127]
Original ticket: https://github.com/pepfar-datim/Global/issues/3984

Limit the users in the users list to only users that the person logged in has access to view/edit.

This is low priority and not essential for MVP (minimally viable product)

**Comment by DavidNesbitt** [comment]
You can also reference https://github.com/pepfar-datim/Global/issues/3624 for additional information on the listed users a user admin can see  (by their user account type: partner/agency/moh/etc)

**Comment by jakub-bao** [comment]
I think this is done.
