### ISSUE TITLE
REACT User admin: Management Dashboards to Global and Inter-Agency users

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#128]
Original Requirements: https://github.com/pepfar-datim/Global/issues/3550

1. In the new **REACT**  version of User Admin, All Global and Inter Agency users should have the HQ Dashboard Viewer role added automatically.
[@jakub-bao - number 1 might already be developed]

2. Also display the permission as "automatically granted" on the invite screen and info screen for Global and Inter-Agency users:

Example mock-up:
![image](https://user-images.githubusercontent.com/23367121/56005041-7808b180-5c9c-11e9-9bd5-998b5f692159.png)

**Comment by jakub-bao** [comment]
**Global** & **Inter-Agency** is getting **HQ Dashboard Viewer** role

**Comment by jakub-bao** [comment]
Note:

1. Automatically grant `HQ Dashboard Viewer` - not done. will do today.

2. Display as automatically granted data action - will do.

**Comment by jakub-bao** [comment]
1. Automatically grant HQ Dashboard Viewer - done..
2. Display as automatically granted data action - in progress...

**Comment by hkim224** [comment]
Agency HQ should also get the HQ Dashboard Viewer

**Comment by jakub-bao** [comment]
Update:
1. Global user will get `HQ Dashboard Viewer` - done
2. Agency HQ will get `HQ Dashboard Viewer` - done
3. Global will get `Dedupe dashboard app` - done
4. Agency HQ will get  `Dedupe dashboard app` - done
5. Roles will be displayed for both Global & Agency HQ as automatically granted in both Invite & Edit page - in progress

**Comment by jakub-bao** [comment]
Done.

![image](https://user-images.githubusercontent.com/47790868/57240891-b8d6ba80-6ffd-11e9-8707-f1db27e39953.png)

Per discussion with @hkim224 we decided to not display the privileges as automatically granted for now.

**Comment by jakub-bao** [comment]
This should appear for `Global`, `Inter-Agency`, `Agency HQ`.. one is most likely missing..
