### ISSUE TITLE
"Unapproved Data Viewer" role

### ISSUE THREAD

**Issue by Awnage** [pepfar-datim/datim-user-management-ng#13]
What is this role and why do agency and IA_SUA users have it? @hardingt

**Comment by hardingt** [comment]
@Awnage so they can create Agency users. The plan after MVP was done was to add Inter agency Super User as a user type.

**Comment by jakub-bao** [comment]
SI Liaison - role - check with ben

**Comment by jakub-bao** [comment]
Not to be done right now. Current workaround: Agency users create other agency accounts.
