### ISSUE TITLE
Visual enhancement: Enlarge User Admin landing page?

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#130]
@jakub-bao 
On my 1920x1080 resolution laptop, the visual display of the REACT admin page on dev.datim (through Chrome) is kind of small (my browser view is set to 100% zoom).  Can we enlarge some of the clickable/selectable options?
This might be due to my aforementioned configuration though

![image](https://user-images.githubusercontent.com/23367121/56052958-ba73d200-5d20-11e9-9655-0ae551a4b3d2.png)

FYI: @hkim224

**Comment by jakub-bao** [comment]
@DavidNesbitt Hi David, do you have 15" laptop at 1920*1080p ? 
Yeah I bet it can look small.. I'll think about what to do...

**Comment by jakub-bao** [comment]
Made the icons a bit bigger...
