### ISSUE TITLE
Add enable/disable action/buttons on edit user page

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#136]
Moving ticket from global repo (https://github.com/pepfar-datim/Global/issues/3977) to REACT repo here:

On the REACT App edit user page, there should be an actionable button where the user administrator can either enable or disable the user.

![image](https://user-images.githubusercontent.com/23367121/56294373-e6b09980-60f8-11e9-8cf3-a06e1ee91dee.png)

**Comment by jakub-bao** [comment]
Done

![image](https://user-images.githubusercontent.com/47790868/56440746-65076a00-62b8-11e9-93a0-db0e90a51260.png)
