### ISSUE TITLE
Add enable/disable buttons on the user details box

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#137]
moving from global repo https://github.com/pepfar-datim/Global/issues/3976

Add enable/disable buttons on the user details box.
![image](https://user-images.githubusercontent.com/23367121/56299693-89214a80-6102-11e9-8cab-38a88847c53c.png)

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/56761565-a93cb380-676b-11e9-8427-b23b808394b0.png)

**Comment by jakub-bao** [comment]
Done.

**Comment by jakub-bao** [comment]
had to refactor the app a bit.
