### ISSUE TITLE
Agency HQ needs to be at the "Global" level

### ISSUE THREAD

**Issue by hardingt** [pepfar-datim/datim-user-management-ng#14]
Thanks for getting the user type in there! Here's an example `Agency HQ` user:

test_agency_hq_ua

https://newrelease-manual.datim.org/dhis-web-maintenance-user/showUpdateUserForm.action?id=110046712

Let me know what you think about adding an OU level to the json file to denote where these user types are valid.
![image](https://user-images.githubusercontent.com/368749/44228290-f4291480-a162-11e8-851f-c8f8f0a94164.png)
![global level](https://user-images.githubusercontent.com/368749/44228336-128f1000-a163-11e8-8d45-d6323f2cc355.gif)

**Comment by Awnage** [comment]
ready for testing

**Comment by hardingt** [comment]
@Awnage will do!

**Comment by hardingt** [comment]
@Awnage almost, we need an agency type now:

![image](https://user-images.githubusercontent.com/11567315/44416040-e3e8af00-a53f-11e8-8b5b-843db81e3e9a.png)

I agree it isn't up there in the reqs :D I missed it and there is no easy way to assign that in our config.js file at the moment.

Essentially a superset of all Agencies, but these are assigned at the global level:

https://newrelease-manual.datim.org/dhis-web-maintenance-user/getAllUserGroups.action?key=Global+Agency&curKey=

here are the groups in question. They work the same way as a non global agency.

**Comment by Awnage** [comment]
Something like this:![Screen Shot 2018-08-21 at 10.01.43 AM.png](https://images.zenhubusercontent.com/59a6bc918f62dc7798c49992/33091170-99ff-4221-8a0d-772a6494e0b6)

**Comment by hardingt** [comment]
@Awnage yes exactly!

**Comment by hardingt** [comment]
And instead of assigning: `OU Angola Agency HHS/CDC users` (as it would for Angola DOD), it would assign `Global Agency HHS/CDC users` instead.

**Comment by Awnage** [comment]
Ready for testing @hardingt
