### ISSUE TITLE
Editing a user: "Saved" changes system notification

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#140]
on dev.datim: In the edit user page, the banner for "Changes Saved" pop-up at bottom of page has been removed, and now a tiny, off-center pop-up appears at the top:

![image](https://user-images.githubusercontent.com/23367121/56303446-f1275f00-6109-11e9-9191-eebde76c8a40.png)

When I edited a user, I didn't see that my changes were saved by the system. I had to scroll up to find the above notification.

@jakub-bao - I don't know if you've since changed this, but I think it's bad UI functionality (too ambiguous).  Please add back the previous banner at the bottom, or enhance this notification to be clear to users that their saved changes have been captured by the system.

fyi @hkim224 @benguaraldi

**Comment by jakub-bao** [comment]
Done... replaced by snackbar messages...

![image](https://user-images.githubusercontent.com/47790868/57155807-5f2a8200-6daa-11e9-8ca0-6017ad3d87c4.png)
