### ISSUE TITLE
Global User Configuration

### ISSUE THREAD

**Issue by hkim224** [pepfar-datim/datim-user-management-ng#143]
@jakub-bao please see below for the standard configuration for a Global User. Please note that in the current Angular app, the HQ Dashboard Viewer is not conferred, but it should be.

Global User:
![image](https://user-images.githubusercontent.com/23666620/56390262-a258f280-61f9-11e9-9520-8655fdb2e6cf.png)

Global User who is a User Manager:
![image](https://user-images.githubusercontent.com/23666620/56390317-c6b4cf00-61f9-11e9-969a-f56fda7b1313.png)

**Comment by jakub-bao** [comment]
Thanx. Solved as this ticket: https://github.com/pepfar-datim/datim-user-management-ng/issues/155
