### ISSUE TITLE
Agency HQ & SuperAdmin users should be able to invite Agency HQ User

### ISSUE THREAD

**Issue by hkim224** [pepfar-datim/datim-user-management-ng#144]
@jakub-bao see below for an example Agency HQ configuration.

Please note that the user groups should apply as follows:
- Global Agency {Agency name} all mechanisms
- Global Agency [Agency name] users
- where {Agency name]  is determined by the which Agency is selected when the user account is created, i.e. HHS/CDC, DOD, PC, etc.

While there are currently no Agency HQ user administrators, this permission should be allowed in the REACT app. Agency HQ users should be able to invite other Agency HQ users.

![image](https://user-images.githubusercontent.com/23666620/56391291-39bf4500-61fc-11e9-8ca4-9d972975cbc1.png)

**Comment by jakub-bao** [comment]
Got it. So the user story is:

`Agency HQ` type of user from `Agency 1` who is also `user admin` should be able to invite another `Agency HQ` type of user to `Agency 1` as well as `Partner` and `Agency` type of users.

Can they also invite `Agency HQ User Admin`, `Agency User Admin` & `Partner User Admin`? 

Thanks, Harry.

**Comment by hkim224** [comment]
Agency HQ type of user from Agency 1 who is also user admin should be able to invite another Agency HQ type of user to Agency 1 as well as Partner and Agency type of users. - **Is it possible for Agency HQ users to only invite agency and partner users for ER only? I'm wondering if this will cause any issues for partners who have both MER and ER privileges.**

Can they also invite Agency HQ User Admin, Agency User Admin & Partner User Admin? - **YES**

**Comment by jakub-bao** [comment]
Hey, I got a bit confused. Thanx for posting the configuration for Agency HQ.

However, I am looking on `Agency` (non-HQ) user and I see actually more groups & roles.
Is that normal:

![image](https://user-images.githubusercontent.com/47790868/56827024-a3a6a280-682b-11e9-9240-83f79338b3b1.png)

![image](https://user-images.githubusercontent.com/47790868/56827037-ac977400-682b-11e9-966d-dd9f5cf9b799.png)

**Comment by hkim224** [comment]
So Agency HQ only gets access to ER data, they don't have access to anything else - this means their roles and groups are limited (I assume this might become problematic when inviting other user types).

**Comment by jakub-bao** [comment]
@hkim224 OK, I got it now. So `Agency HQ` can only view `ER` data.

Can `Agency HQ` invite `Agency` user which can view `MER` or `SASR` or `SIMS` data?

**Comment by hkim224** [comment]
So I think if we restrict Agency HQ to ER data, that person can probably only invite other users to ER data, not any of the other streams - @benguaraldi is that correct?

**Comment by benguaraldi** [comment]
Referring to @hardingt who can actually keep all of this in his head.

**Comment by hardingt** [comment]
@hkim224 that should be correct. I'm fine with keeping Agency HQ users out of the business of making any other account types right now if you are.

**Comment by jakub-bao** [comment]
Notes from call with @hkim224 

Current Angular app doesn't let users to create `Agency HQ` users.
However, REACT needs to do that.

`Agency HQ` user is tied to (OU) Global.
`Agency HQ` user can only invite `Agency HQ` user of same type / agency.

**Comment by jakub-bao** [comment]
Adding `super-user` to the menu per @benguaraldi (slack conversation)

**Comment by benguaraldi** [comment]
@jakub-bao, I'm confused.  What menu are you adding it to?

**Comment by jakub-bao** [comment]
Haha.. sorry.

Per our Slack chat.

`Super-User` should be able to invite `Agency HQ`

The original requirement was only: `Agency HQ` should be able to invite `Agency HQ`

So after our chat I'll do both. OK?

**Comment by benguaraldi** [comment]
Sounds good!

**Comment by jakub-bao** [comment]
Done.
