### ISSUE TITLE
DoD Partner User Configuration

### ISSUE THREAD

**Issue by hkim224** [pepfar-datim/datim-user-management-ng#146]
The option for Data Entry DoD is available when a partner is selected who is associated with a DoD mechanism.

The following selections in the user admin app,
![image](https://user-images.githubusercontent.com/23666620/56445060-5a090580-62c9-11e9-8b14-b666f9ad6e2c.png)

result in the following configuration on the backend (note that the user group is Data PRIME Entry DoD - outside of this the configuration is the same as a regular partner):
![image](https://user-images.githubusercontent.com/23666620/56445470-6726f400-62cb-11e9-94a7-66cb0c82bd43.png)

@jakub-bao

**Comment by jakub-bao** [comment]
Done.
