### ISSUE TITLE
Test case on REACT version

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#149]
Test the "myanmar" font selection bug in the REACT app version (once on a stable test environment)

https://github.com/pepfar-datim/Global/issues/3185

**Comment by jakub-bao** [comment]
I think it's fixed.
Screenshot below when appearance set to `Myanmar`

![image](https://user-images.githubusercontent.com/47790868/56823322-84a31300-6821-11e9-9db6-0e80b9dd464e.png)
