### ISSUE TITLE
`Global User UA` created in REACT vs Angular app

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#156]
Hi @hkim @DavidNesbitt @hardingt 

I found one discrepancy between the `REACT` & `Angular` versions.

Steps to reproduce:
1. Login as `Superuser ALL authorities`
2. Invite a `Country:Global` & `Type:Global` & `User Manager` user inside Angular & REACT app
3. The two new users will have different `roles` & `user groups` (see screenshots below)

REACT gives the Global user `Data Entry Tracker` role & `Funding Mechanisms` dimension.
Angular leaves these out.

Question: **Which one is the truth?** The Angular or the REACT version of the user? Thanx!

**Comment by jakub-bao** [comment]
Screenshot #1: `Global` user created by REACT:

![image](https://user-images.githubusercontent.com/47790868/56834718-2e919800-6840-11e9-894b-6d2dd13d565e.png)

![image](https://user-images.githubusercontent.com/47790868/56834743-3f420e00-6840-11e9-91e2-bc1f4f5554f2.png)

**Comment by jakub-bao** [comment]
Screenshot #2: `Global` user created in Angular app:

![image](https://user-images.githubusercontent.com/47790868/56834803-6c8ebc00-6840-11e9-868f-ee4866ec7ac4.png)

**Comment by benguaraldi** [comment]
I'm pretty sure that the angular app is correct.

@hardingt?

**Comment by jakub-bao** [comment]
@benguaraldi OK, shouldn't be hard to fix for me...

**Comment by jakub-bao** [comment]
Fixed.
The following user was created by REACT app: 

![image](https://user-images.githubusercontent.com/47790868/56903451-506e6300-6a6a-11e9-8a08-ec0c43bc87e8.png)

![image](https://user-images.githubusercontent.com/47790868/56903468-5b28f800-6a6a-11e9-87b2-04486314f19e.png)

Simple fix: 
![image](https://user-images.githubusercontent.com/47790868/56903491-6ed45e80-6a6a-11e9-807d-891fc0b05d30.png)

**Comment by benguaraldi** [comment]
Reopening so that @hardingt can verify that the angular app is correct.

**Comment by hardingt** [comment]
@benguaraldi and @jakub-bao shouldn't we not be using the normal user + Global button at all?

![image](https://user-images.githubusercontent.com/11567315/56961731-866f1e00-6b22-11e9-9448-d844954cf7ac.png)

IIRC it's some kind of broken feature, All global users should be created with the:
![image](https://user-images.githubusercontent.com/11567315/56961752-98e95780-6b22-11e9-98f7-ca7598b0fd3f.png)

at which point the user looks like:
![image](https://user-images.githubusercontent.com/11567315/56961793-c46c4200-6b22-11e9-93e5-162f3bf5b3ac.png)

and

![image](https://user-images.githubusercontent.com/11567315/56961804-ca622300-6b22-11e9-9989-5bfa2bf968cc.png)

**Comment by benguaraldi** [comment]
@hardingt is correct, we shouldn't be using the angular DATIM user administration app's `Invite user` button to create a Global user.

Note that in the react app, there should only be one invite button, but in the angular app there are two.

@jakub-bao, please confirm that the angular `Invite Global user` and the react `Invite user` do the same thing.  Thanks!

**Comment by jakub-bao** [comment]
@hardingt @benguaraldi 

The old Angular app has two buttons `Invite User` & `Invite Global User`

The REACT version will have just one button `Invite User`.
You'll be able to invite `Global` user just using the  `Invite User`, because the list of countries is equipped by `Global`...

See screenshot below... (that's the new Invite page)

![image](https://user-images.githubusercontent.com/47790868/56986183-18454e00-6b58-11e9-8205-3df9475fe627.png)

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/56986206-2abf8780-6b58-11e9-8af9-8a5473772842.png)

**Comment by benguaraldi** [comment]
@jakub-bao Great!  Now, the real kicker: When you invite a global user with the react app, does it have the same roles and groups as when you invite the user (in the right way, not the wrong way) with the angular app?

**Comment by jakub-bao** [comment]
@benguaraldi Good point! So it **was** broken. The users would be different. 
However, I've fixed in this ticket. So now:

`Global` user created by `Invite Global User` inside `Angular` app is **the same as**
`Global` user created by `Invite User` by the new `REACT` app.

**Comment by jakub-bao** [comment]
@benguaraldi I think we're done here.. can we close the ticket?

**Comment by benguaraldi** [comment]
Yup! Thanks!
