### ISSUE TITLE
`Agency HQ UA` user can't edit anyone

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#164]
It just looks a little strange so I want to double-check with you guys...

Created `Agency HQ` / `User Admin` / `HHS/CDC`

Can't find a single user he could edit...

![image](https://user-images.githubusercontent.com/47790868/57023763-e63bf680-6c00-11e9-9b77-faa548b9fff6.png)

**Comment by jakub-bao** [comment]
FYI, this seems to be the reason... Doesn't seem right:

![image](https://user-images.githubusercontent.com/47790868/57023640-8e04f480-6c00-11e9-806f-5f9180e74fc4.png)

**Comment by jakub-bao** [comment]
Questions:

Can `Agency HQ UA` user manage `Agency` users?

Should `Agency HQ` get `Unapproved Data Viewer` role?

**Comment by hardingt** [comment]
@jakub-bao Agency HQ users _cannot_ edit Agency users at the moment. This is due to the unapproved data viewer role you are correct. At the moment the Agency HQ users are not in charge of editing any other user type.

**Comment by jakub-bao** [comment]
Per @benguaraldi 

1) The warning message is very close—instead of "Global" it should say "Agency HQ"

**Comment by benguaraldi** [comment]
Probably we should do the same thing with Agency HQ users that we do with Global based on this comment: https://github.com/pepfar-datim/datim-user-management-ng/issues/158#issuecomment-488729232
