### ISSUE TITLE
Bug: Filter by `User Type: Global` returns also `User Type: Agency HQ`

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#170]
![image](https://user-images.githubusercontent.com/47790868/57101883-35148980-6cf0-11e9-85ac-d8f176917168.png)

**Comment by srihtanguturi** [comment]
Same behavior was noticed with other user types.

1. Logged in Global user admin (globaltester2)
2. Filtered the users list by User Type as "Partner"
Expected that search results will filter and display only Partner users.

![image](https://user-images.githubusercontent.com/24919495/57938024-379ce480-7895-11e9-8389-181c0bd20858.png)

**Comment by jakub-bao** [comment]
fixed.
