### ISSUE TITLE
Unable to reset passwords

### ISSUE THREAD

**Issue by chazhall54** [pepfar-datim/datim-user-management-ng#175]
Environment: https://ng.testing.datim.org
User: Super
App: User 29.0.2
Browser: Chrome and Firefox

Steps to Reproduce:

- As a "Super" user, go to the User app and search for a user (tried partnertesterua1 and globaltest1)

- Enter a new password, save and wait for the page to redirect

- Login as the resetted user

Expected Result: To be able to login

Actual Result: I receive the error "Your account is locked"

<img width="1440" alt="Screen Shot 2019-05-14 at 1 13 10 PM" src="https://user-images.githubusercontent.com/6374474/57717833-0e3c4880-764a-11e9-93eb-a111db5c1d8d.png">

<img width="1440" alt="Screen Shot 2019-05-14 at 1 14 32 PM" src="https://user-images.githubusercontent.com/6374474/57717949-45125e80-764a-11e9-86ab-04a95d336a3b.png">

**Comment by jakub-bao** [comment]
@oodujebe @chazhall54 ... This is a bug in the DHIS2 Native Users app.

However, the one we're providing is the DATIM User App:
https://ng.testing.datim.org/api/apps/User-Administration/index.html#/
