### ISSUE TITLE
Invite User - Occasional "Invitation error: code 700" responses

### ISSUE THREAD

**Issue by mpinardi-bao** [pepfar-datim/datim-user-management-ng#176]
When attempting to invite a user it is possible that a error will be returned to the user even though the email is sent on the back end.
Reproduce error (I don't think it always sends when you do this way):
(used a MOH user)
1. Go to invite page https://ng.testing.datim.org/api/apps/User-Administration/index.html#/invite
2. Refresh the page
3. Quickly select a email and send
4. Error will appear.

I have also had this issue appear under normal usage.

**Comment by jakub-bao** [comment]
@mpinardi-bao good. thanks for catching that...

Where did you see the error?
Did it popup in the bottom as the black pop-up banner?

Did you see the error also in your dev-tools/network?

**Comment by mpinardi-bao** [comment]
It popped up in the bottom as a black banner as you stated.
I didn't validate the responses on the network side (I can loop back tomorrow if you want)

**Comment by mpinardi-bao** [comment]
Invitation error {httpStatus: "Conflict", httpStatusCode: 409, status: "ERROR", message: "You must have permissions to create user, or ability to manage at least one user group for the user."}
(anonymous) @ Invite.component.js:677
Promise.catch (async)
n.handleInviteUser @ Invite.component.js:675
(anonymous) @ react-dom.production.min.js:14
d @ react-dom.production.min.js:15
(anonymous) @ react-dom.production.min.js:15
S @ react-dom.production.min.js:17
T @ react-dom.production.min.js:18
O @ react-dom.production.min.js:18
j @ react-dom.production.min.js:21
kn @ react-dom.production.min.js:84
Au @ react-dom.production.min.js:250
Ne @ react-dom.production.min.js:39
Tn @ react-dom.production.min.js:86
(anonymous) @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Iu @ react-dom.production.min.js:251
En @ react-dom.production.min.js:85

**Comment by jakub-bao** [comment]
@mpinardi-bao awesome! thanks for the details 👍

**Comment by jakub-bao** [comment]
per meeting with @mpinardi-bao .. use "mohtesterua1" user

**Comment by jakub-bao** [comment]
so I've got a hunch this has to do with timing of requests... why? no idea....

![image](https://user-images.githubusercontent.com/47790868/57794844-8ec67c00-7712-11e9-95a1-b619af1f3a1b.png)

screenshot above shows .. unsuccessful invite (which was sent before `userGroups` query finished)
and a successful invite (fired after the `userGroups` query came back)

the server is sending us an error that we don't belong to MOH groups:

![image](https://user-images.githubusercontent.com/47790868/57794941-d0efbd80-7712-11e9-82e8-88747cc279f3.png)


so i guess these two facts are related... however it almost seems like a bug in DHIS2..

anyways .. i am going to block sending invites until the userGroups query comes back...

**Comment by jakub-bao** [comment]
@mpinardi-bao resolved. can you please re-test and close the ticket?

https://ng.testing.datim.org/api/apps/User-Administration/index.html#/

**Comment by mpinardi-bao** [comment]
Seems fixed.
