### ISSUE TITLE
Inconsistent behavior with Active/Disable toggle

### ISSUE THREAD

**Issue by oodujebe** [pepfar-datim/datim-user-management-ng#177]
Environment: https://ng.testing.datim.org
**User**: Super
**App**: User Administration v29.0.2
**Browser**: Chrome

**Steps to reproduce**:

1. Login to DATIM as Super user
2. Navigate to: https://ng.testing.datim.org/api/apps/User-Administration/index.html#/
3. Toggle Active/Disable on any user in the list

**Expected Result**: To be able to consistently activate/disable a user.

**Actual Result**: At some point after activating/disabling a user, the toggle stops responding, and the user interface keeps displaying the same state as previously displayed. When the application is refreshed, the state sometimes displays the previous state, other times, it displays the same state.

![image](https://user-images.githubusercontent.com/22481511/57722840-5c0a7e00-7655-11e9-97f8-660e481b153e.png)

**Comment by jakub-bao** [comment]
hi @oodujebe .. good job finding this.

can you tell me how exactly to reproduce..

did you disable/enable a single user multiple times quickly?
or did u disable/enable different users?

**Comment by oodujebe** [comment]
@jakub-bao yes, disable/enable a single user multiple times quickly?

It appears the app does not mask the clicks, before the state changes, so it eventually gets out-of-sync.

**Comment by jakub-bao** [comment]
@oodujebe got ya.. will fix!

**Comment by jakub-bao** [comment]
@oodujebe resolved. can you re-test and close the ticket? 

https://ng.testing.datim.org/api/apps/User-Administration/index.html#/

**Comment by oodujebe** [comment]
@jakub-bao I'm still experiencing some issues. Please see the screencast below.

The initial toggle works, subsequent toggles provide inconsistent results.

I did clear my cache, and force a hard reload before my re-test.

![active_disable_toggle](https://user-images.githubusercontent.com/22481511/58207369-8b9e3380-7cb0-11e9-83d7-7896140e2afe.gif)

**Comment by jakub-bao** [comment]
I am blaming DHIS2 cache.

User is enabled:
![image](https://user-images.githubusercontent.com/47790868/58273458-c363b480-7d5e-11e9-959d-122f662822b4.png)

The app sends this request to disable user:
![image](https://user-images.githubusercontent.com/47790868/58273433-b777f280-7d5e-11e9-8f84-a1895fb11886.png)

Right after the action the app re-fetches the user however the user is NOT disabled yet:
![image](https://user-images.githubusercontent.com/47790868/58273525-e55d3700-7d5e-11e9-8867-040c85c53581.png)

However, if you check via API few seconds later .. the user is finally disabled:

**Comment by jakub-bao** [comment]
I guess the only solution which is in my mind right now is to put 1 second extra wait...

**Comment by oodujebe** [comment]
Does the api ever respond with a confirmation of the request? Vs extending the duration, can you hide the mask after the response from the api returns?

**Comment by jakub-bao** [comment]
@oodujebe yes it does. and i do exactly that.
however, that is not enough.

Basically you shoot a request to the API and the API replies withing 300-600ms.
After that I reload the state of the user.

But sometime it takes DHIS2 about 6-7 seconds before they return me the correct state.

I am about to talk to @chuqyang about this. If we can dig into the DHIS2 cache a bit.

**Comment by jakub-bao** [comment]
Note after a call with @chuqyang 

There are 4 possible places where the user can get cached:

1. Redis (it's unlikely)
2. AWS Load Balancer (unlikely)
3. Tomcat (possible)
4. DHIS2 cache on filesystem (possible)

We've kind off ruled off 1. & 2. during the call.

I'll take a look at 3. & 4. and update this issue tomorrow.

@benguaraldi @hardingt any suggestions from your side?

**Comment by jakub-bao** [comment]
OK, very good lead is this:

https://docs.dhis2.org/2.30/en/implementer/html/dhis2_implementation_guide_full.html#install_application_cache_providers

DHIS2 uses `memcached` with default settings of 10seconds.

**Comment by jakub-bao** [comment]
So, our DHIS2 instance at `ng.testing.datim.org` doesn't seem to use `memcached`.
However, it's using `redis`. @chuqyang explained to me how to connect to redis.

I'll find out if they cache the users objects there and if there is system settings we can change to limit the cache time from default 10seconds to let's say 1second only.

**Comment by benguaraldi** [comment]
@jakub-bao Could we do something like this:
1. Get the response from the API and change the user interface based on that
2. Reload the state of the user 10 seconds later
3. If there looks like there was a problem based on the reloaded state, generate an error message then
?

**Comment by jakub-bao** [comment]
Hey @benguaraldi ... unfortunately even 10 seconds is not enough :(

I am working on this with @chuqyang 

The prob is that the server `ng.testing` is running as a cluster .. which will be the future setting for DATIM production as well.

DHIS2 nodes running in cluster are supposed to communicate together and tell each other to wipe out cache of an object if it gets updated.
This for some reason fails.

We have a quick workaround solution: https://github.com/pepfar-datim/Global/issues/5005

And then hopefully we'll find the proper solution as well: https://github.com/pepfar-datim/Global/issues/5003

Let's let this ticket to sit here and I'll get back and update you guys when we have the workaround and we can re-test it then.

**Comment by benguaraldi** [comment]
@jakub-bao Roger.  I thought it was a DHIS2 problem, not an ng.testing problem.  Carry on.  :)

**Comment by jakub-bao** [comment]
I've reached to DHIS2 folks via their Slack channel and they directed me this way:
https://github.com/pepfar-datim/datim-user-management-ng/issues/188

First of all we should get rid of `HTTP PATCH` since they admit it doesn't work very well.

**Comment by hardingt** [comment]
@jakub-bao agreed on `PATCH`, it was never fully supported for users. After much back and forth with Greg and Oslo, I'm not sure all the bugs were ever worked out.

**Comment by oodujebe** [comment]
This might be related to this issue. https://jira.dhis2.org/browse/DHIS2-6708

**Comment by jakub-bao** [comment]
@hardingt @oodujebe Unfortunately, switching from `PATCH` to `PUT` doesn't solve the issue.

Steps to reproduce here: https://youtu.be/KN4xjAuvsAA

We'll try to fix this with @chuqyang Will post update here later this week.

**Comment by hardingt** [comment]
@jakub-bao what about switching to `POST`? This is how I seed and update users for test environments.

**Comment by jakub-bao** [comment]
@hardingt I don't think it will make much difference.
The issue is in DHIS2 cluster configuration.

Anyways, the issue is somewhere in-between DHIS2 / cluster configuration.. So I'm postponing work on this.

I've checked with @chuqyang and 2.30 is not going to production as a cluster.
Before going to cluster settings on prod we'll need to make sure this is resolved.

Linking JIRA issue for UiO here: https://jira.dhis2.org/browse/DHIS2-7038

**Comment by jakub-bao** [comment]
Oh, finally we almost done!
@chuqyang found there was some firewall issue blocking communication between the servers! Yay!

I just need to put in 1second delay after disabling/enabling user.
It's still possible to reproduce the issue if you click really really fast.

But the core underlying issue is gone...!

**Comment by oodujebe** [comment]
After this issue  (https://jira.dhis2.org/browse/DHIS2-6708) was resolved. This is working as intended.
