### ISSUE TITLE
Promote user to useradmin fails for MOH user admin

### ISSUE THREAD

**Issue by mpinardi-bao** [pepfar-datim/datim-user-management-ng#178]
I have seen twice now where an attempt to saved a edited user fails.
This same user is able to edit and promote another user.

Example Scenario:
  Background: These steps need to be executed
    Given Login to dhis2 with "MOHUA"   #mohtesterua1
 And Navigate to Users Administration

Scenario: Promote user
When Edit UserAdmin user "mohtester1"
And Set UserAdmin user to admin
And Save UserAdmin user
Then Verify UserAdmin user has saved.

Error: 
Edit.component.js:411 Save failure: {klass: "org.hisp.dhis.user.User", index: 0, uid: "wZJ7RgjmiCS", errorReports: Array(1)}errorReports: Array(1)0: errorCode: "E3005"mainKlass: "org.hisp.dhis.user.UserGroup"message: "User `{"id":"123330182", "uid":"B8sTe8sC4gx", "code":"null", "created":"2019-01-07 17:26:11.448", "lastUpdated":"2019-05-15 13:31:25.015", "surname":"2fa5d9e3-b0ae-4", "firstName":"79977f0d-8", "email":"63db4c08@67f5ceb6.com", "phoneNumber":"0-0-1", "jobTitle":"null", "introduction":"null", "gender":"null", "birthday":"null", "nationality":"null", "employer":"null", "education":"null", "interests":"null", "languages":"null", "lastCheckedInterpretations":"null", "userCredentials":"{"username":"mohtesterua1", "openId":"null", "password":"$2a$10$4ggfYUI1Q0nVA2qB93D.g.ca5b.GIj5jTJ3eDgZ1XmLJLqgdHAX12", "passwordLastUpdated":"2019-05-15 13:31:18.754", "userAuthorityGroups":"[{"class":"class org.hisp.dhis.user.UserAuthorityGroup", "id":"494960", "uid":"k7BWFXkG6zt", "code":"null", "name":"Data Entry Aggregate", "created":"2014-02-20 08:49:58.841", "lastUpdated":"2019-05-14 15:03:27.174" }, {"class":"class org.hisp.dhis.user.UserAuthorityGroup", "id":"494962", "uid":"KagqnetfxMr", "code":"null", "name":"User Administrator", "created":"2014-02-20 03:57:43.415", "lastUpdated":"2019-05-15 13:42:17.913" }, {"class":"class org.hisp.dhis.user.UserAuthorityGroup", "id":"494959", "uid":"b2uHwX9YLhu", "code":"null", "name":"Read Only", "created":"2014-02-20 03:47:44.417", "lastUpdated":"2019-05-15 13:42:27.175" }]", "lastLogin":"null", "restoreToken":"null", "restoreCode":"null", "restoreExpiry":"null", "selfRegistered":"false", "disabled":"false" }", }` is not allowed to grant users access to user group `{"class":"class org.hisp.dhis.user.UserGroup", "id":"0", "uid":"WGrMD2jPhP4", "code":"null", "name":"null", "created":"null", "lastUpdated":"null" }`."__proto__: Objectlength: 1__proto__: Array(0)index: 0klass: "org.hisp.dhis.user.User"uid: "wZJ7RgjmiCS"__proto__: Object
(anonymous) @ Edit.component.js:411
Promise.then (async)
n.handleEditUser @ Edit.component.js:401
(anonymous) @ react-dom.production.min.js:14
d @ react-dom.production.min.js:15
(anonymous) @ react-dom.production.min.js:15
S @ react-dom.production.min.js:17
T @ react-dom.production.min.js:18
O @ react-dom.production.min.js:18
j @ react-dom.production.min.js:21
kn @ react-dom.production.min.js:84
Au @ react-dom.production.min.js:250
Ne @ react-dom.production.min.js:39
Tn @ react-dom.production.min.js:86
(anonymous) @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Iu @ react-dom.production.min.js:251
En @ react-dom.production.min.js:85

**Comment by jakub-bao** [comment]
@mpinardi-bao awesome again. thanks! will fix. 👍

**Comment by jakub-bao** [comment]
per @mpinardi-bao meeting... to reproduce login as `mohtesterua1` and try to give user manager permission to `mohtester1`

**Comment by jakub-bao** [comment]
but it's working for Patrick Tem

**Comment by jakub-bao** [comment]
I've did a compare of a user we can promote and we cannot promote.. they differ in these privileges..
I'll test one by one if any of them is the dealbreaker...

![image](https://user-images.githubusercontent.com/47790868/57802324-ace8a800-7723-11e9-8426-82442c0d9924.png)

**Comment by jakub-bao** [comment]
Okay.. found the error (well same as @mpinardi-bao 

![image](https://user-images.githubusercontent.com/47790868/57877785-a111ea00-77e6-11e9-8b65-ed36ce9c6001.png)

**Comment by jakub-bao** [comment]
User `mohtesterua1` is not allowed to grant user access to user group `id:WGrMD2jPhP4`

**Comment by jakub-bao** [comment]
The prob is that `mohtesterua1` is a member of `OU Botswana all mechanisms`:

![image](https://user-images.githubusercontent.com/47790868/57878350-d539da80-77e7-11e9-804a-ddf217624658.png)

**Comment by jakub-bao** [comment]
@hardingt just explained to me.

The user `mohtester1` is setup wrong.
It's a MOH user however he is a member of `OU Botswana all mechanisms`

MOH users should not be members of `all mechanisms`.
Any MOH user created via Angular or REACT app won't be member of `all mechanisms`.

I'll go through triage.datim.org to double-check if this is also an issue in production.
If yes, I'll file a ticket and we'll need to fix how these users are setup.

**Comment by jakub-bao** [comment]
Hi, so with Tim's help I got a SQL script to find users who are `MOH` however, they have the `all mechanisms` group and therefore they won't be manageable by new REACT app.

```
select u.userid,u.username, u.lastlogin, ug.usergroupid, ug.name into mohusers
from users u
join usergroupmembers m
on u.userid=m.userid
join usergroup ug
on m.usergroupid = ug.usergroupid
where ug.name like 'OU % MOH Users';

select u.userid,u.username, u.lastlogin, ug.usergroupid, ug.name into allmechanisms
from users u
join usergroupmembers m
on u.userid=m.userid
join usergroup ug
on m.usergroupid = ug.usergroupid
where ug.name like '% all mechanisms'
or ug.name like '% All mechanisms';

select * from mohusers;
select * from allmechanisms;

select * from mohusers join allmechanisms on mohusers.userid = allmechanisms.userid;

drop table mohusers;
drop table allmechanisms;
```

![image](https://user-images.githubusercontent.com/47790868/57950178-89a13280-78b4-11e9-9c60-4596d4fa27fc.png)

@hkim224 @benguaraldi @hardingt Can we remove the `all mechanisms` group for these users?
