### ISSUE TITLE
After saving Data Streams, permissions change to a different set of permissions

### ISSUE THREAD

**Issue by chazhall54** [pepfar-datim/datim-user-management-ng#180]
Environment: https://ng.testing.datim.org/
All browsers
As a Super user

Test Steps:

- Go to User Admin app and search for a user like agencytester1 or agencytesterua1

- View Data Streams (see first screen shot) 

- Uncheck User Manager and recheck, then save (see second screen shot)

- Press the back button. Then click Edit for the User again. (see third screen shot)

Expected result: Save the user set data stream permissions or revert to the preset

Actual Result: Reverted to a different set of permissions than the user set or preset

<img width="1440" alt="Screen Shot 2019-05-16 at 8 04 58 AM" src="https://user-images.githubusercontent.com/6374474/57854299-eec22e80-77b5-11e9-81bd-ec17d74acd36.png">

<img width="1440" alt="Screen Shot 2019-05-16 at 8 05 48 AM" src="https://user-images.githubusercontent.com/6374474/57854317-fa155a00-77b5-11e9-9c02-0629880a967f.png">

<img width="1440" alt="Screen Shot 2019-05-16 at 8 14 06 AM" src="https://user-images.githubusercontent.com/6374474/57854323-fd104a80-77b5-11e9-952f-4fad1ee62b49.png">

**Comment by jakub-bao** [comment]
@chazhall54 okay, thanks for finding this! will fix.

**Comment by jakub-bao** [comment]
after a call with @chazhall54 I am 95% sure this is issue because of DHIS2 cache.. we can't fix that :(

**Comment by jakub-bao** [comment]
closed after discussion with @hkim224 ... this is issue with DHIS2 software itself. not related to the user app code.
