### ISSUE TITLE
Error when signing up as an Invited Partner UA

### ISSUE THREAD

**Issue by chazhall54** [pepfar-datim/datim-user-management-ng#181]
Environment: https://ng.testing.datim.org/
All browsers
As a Invited Partner User

Test Steps:

- Receive invite Email from agencytesterua1 and sign up

Expected result: To get signed in and an a welcome message

Actual Result: Received an error, "Unable to get schemas from the DHIS2 API" (see screenshot below), but the user was created per the User Admin app. 

<img width="1440" alt="Screen Shot 2019-05-16 at 9 43 33 AM" src="https://user-images.githubusercontent.com/6374474/57859739-87aa7700-77c1-11e9-88e3-84b0189a7cfd.png">

**Comment by jakub-bao** [comment]
@chazhall54 Hi, I used to get this error during testing when I would delete user with username `abc1` and then I'd invite new user and they'd select username `abc1`.
That means it would be a DHIS2 bug. We can create a ticket for them.

However, I'd like to double-check it's the same error.

Questions:
1. Do you remember the username you used for signing up?
2. Any chance it was a username of previously deleted user?

**Comment by chazhall54** [comment]
@jakub-bao  I personally never used the username testagenUA, but its possible someone else couldve, its pretty simple. I did use a previously used email datimtest@gmail.com though.

**Comment by srihtanguturi** [comment]
I have noticed that Username and password fields are getting auto-populated upon clicking on the invite link. These fields are supposed to be blank/empty upon clicking on the invite link.

**Invite link:**
https://ng.testing.datim.org/dhis-web-commons/security/invite.action?username=invite-stanguturi@usa-ctc.com-xFIWufpo2zO&token=ICHC6CkrwHh3MU6njazVfZ07pvObpYCU8dkcWgNU7CRaQyNiDGcO

![image](https://user-images.githubusercontent.com/24919495/57939356-38834580-7898-11e9-95b2-009118d4dfd2.png)

**Comment by jakub-bao** [comment]
@srihtanguturi This form is actually not a part of this project. I believe this is designed by DHIS2.
It might be fixed in 2.30. If not we should report this to UiO through their JIRA.

**Comment by jakub-bao** [comment]
@chazhall54 Okay.
Can you send me the username & email you used to create the user?

**Comment by chazhall54** [comment]
Sure @jakub-bao testagenUA and  datimtest@gmail.com

**Comment by chazhall54** [comment]
Good news, created a new user testdatimpartner with datimtest@gmail.com and did not receive the error.

**Comment by jakub-bao** [comment]
I am 98% sure that this is a bug in DHIS2.
I've inspected the logs. During normal invitation this is what happens:
```
* INFO  2019-05-21 20:12:40,299 User test-delete-1 accepted invitation for invite-jflaska@baosystems.com-GU2AQLqAFjW (AccountController.java [http-apr-8081-exec-299])
* WARN  2019-05-21 20:12:40,398 Authentication event AuthenticationSuccessEvent: test-delete-1; details: null (LoggerListener.java [http-apr-8081-exec-299])
* INFO  2019-05-21 20:12:40,401 'system-process' update org.hisp.dhis.user.UserCredentials, name: test delete, uid: c6iM6gGopPt (AuditLogUtil.java [http-apr-8081-exec-299])
* INFO  2019-05-21 20:12:41,560 'test-delete-1' create org.hisp.dhis.userkeyjsonvalue.UserKeyJsonValue, uid: T33xqqf43f1 (AuditLogUtil.java [http-apr-8081-exec-289])
```

Note the last line `'test-delete-1' create` ... meaning user with username 'test-delete-1' is being created..

In case of the `testagenUA` this is what is hapenning:

```
* INFO  2019-05-16 13:43:21,700 User testagenUA accepted invitation for invite-datimtest@gmail.com-ASAsXHaybtO (AccountController.java [http-nio-8081-exec-80])
* INFO  2019-05-16 13:43:21,721 Login attempt: testagenUA (TwoFactorAuthenticationProvider.java [http-nio-8081-exec-80])
* WARN  2019-05-16 13:43:21,833 Authentication event AuthenticationSuccessEvent: testagenUA; details: org.hisp.dhis.security.spring2fa.TwoFactorWebAuthenticationDetails@0: RemoteIpAddress: 10.99.4.105; SessionId: 702db0ee-a98a-4615-8df9-00676a955aa8 (LoggerListener.java [http-nio-8081-exec-80])
* INFO  2019-05-16 13:44:00,005 [Level: INFO, category: LEADER_ELECTION, time: Thu May 16 13:44:00 UTC 2019, message: Leader election completed] (RedisNotifier.java [taskScheduler-3])
* INFO  2019-05-16 13:46:00,005 [Level: INFO, category: LEADER_ELECTION, time: Thu May 16 13:46:00 UTC 2019, message: Leader election completed] (RedisNotifier.java [taskScheduler-4])
```

It doesn't properly create the user in the DB I think.

However, the invite was sent correctly.

**Comment by jakub-bao** [comment]
Also looking directly to the DB.. the user `testagenUA` is not there :(

![image](https://user-images.githubusercontent.com/47790868/58184509-385fbd00-7c7f-11e9-8bcc-fb1bc41e9357.png)

**Comment by jakub-bao** [comment]
Closing for now since it doesn't seem to be related to the user admin app.

**Comment by chazhall54** [comment]
https://jira.dhis2.org/browse/DHIS2-7005

**Comment by jakub-bao** [comment]
@chazhall54 thanks for creating the JIRA ticket for UiO!
