### ISSUE TITLE
View Invite as Global User not working

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#182]
Suddenly this stopped working...

![image](https://user-images.githubusercontent.com/47790868/57883937-9579ef80-77f5-11e9-8160-5fcb262fb865.png)

**Comment by jakub-bao** [comment]
Also Agency HQ

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/57884024-bb9f8f80-77f5-11e9-9b76-d927d1459d6e.png)

**Comment by jakub-bao** [comment]
Browser error...

![image](https://user-images.githubusercontent.com/47790868/57884117-ed185b00-77f5-11e9-9085-92d0bb5c644e.png)

**Comment by jakub-bao** [comment]
We have this issue because we've added `HQ Dashboard Viewer` to be automatically given to `Global` & `Agency HQ` users.

However, existing `Global` & 'Agency HQ' users who don't have `HQ Dashboard Viewer` will not be able to enter the invite page.

Solution #1: Deliver `HQ Dashboard Viewer` to all existing `Global` & `Agency HQ` users...

**Comment by jakub-bao** [comment]
@benguaraldi How do we go about this? Should I write a script which will be a part of the deployment package?

**Comment by benguaraldi** [comment]
@jakub-bao Probably?  I defer to @hardingt on this.

@jakub-bao How many `Global` and `Agency HQ` users don't have `HQ Dashboard Viewer`?  How many of those users are active (i.e., not disabled)?
