### ISSUE TITLE
Deployment script - Add `HQ Dashboard Viewer` to existing users: `Global`, `Inter-Agency`, `Agency HQ`

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#183]
We added a new feature. All new `Global, Agency HQ, Inter-Agency` users will automatically be granted `HQ Dashboard Viewer` role.

However, we need to fix existing users. Specially User Administrators.
Otherwise, these UAs won't be able to edit existing users.
DHIS2 will say that they don't have the `HQ Dashboard Viewer` role.

**Comment by jakub-bao** [comment]
@benguaraldi would u know a good example of a script which does similar thing... ?

**Comment by benguaraldi** [comment]
How about https://github.com/pepfar-datim/Global/blob/master/patches/4047/add_role.py ?

**Comment by jakub-bao** [comment]
done .. pending test & deployment in: https://github.com/pepfar-datim/Global/issues/4980
