### ISSUE TITLE
Unable to send invites

### ISSUE THREAD

**Issue by chazhall54** [pepfar-datim/datim-user-management-ng#193]
Environment: https://pilot-rc.datim.org/api/apps/User-Administration/index.html?v=1.2.2#/add
User: super account, Stanguturi

Steps to Reproduce:

- Go to UA app
- Invite Global or User

Expected: An email to be sent

Actual: I received the below 500 error messages and did not receive the emails.

<img width="1440" alt="Screen Shot 2019-06-19 at 9 36 32 AM" src="https://user-images.githubusercontent.com/6374474/59772075-17d45400-9279-11e9-9b07-2bf00dfdb4b2.png">

<img width="1440" alt="Screen Shot 2019-06-19 at 9 35 42 AM" src="https://user-images.githubusercontent.com/6374474/59772080-1acf4480-9279-11e9-83f7-e792aafa6813.png">

**Comment by jakub-bao** [comment]
@chazhall54 Hi, I've just re-deployed the new REACT version and tested.
It works just fine...

![image](https://user-images.githubusercontent.com/47790868/59779061-93d49900-9285-11e9-9cda-1b3f91687020.png)

**Comment by chazhall54** [comment]
@jakub-bao i was looking at the old app. Good to go thanks!
