### ISSUE TITLE
UI indicates that disabled users cannot be modified (though they can)

### ISSUE THREAD

**Issue by benguaraldi** [pepfar-datim/datim-user-management-ng#204]
When disabled users appear in the list, they look like this:
<img width="838" alt="Screen Shot 2019-09-04 at 9 38 25 AM" src="https://user-images.githubusercontent.com/852673/64261782-0eaf6680-cefb-11e9-8a9e-b76d58ea9512.png">

That gives the impression that the user administrator cannot modify the users, but they can.

Please change the text, icons, and buttons so that they are not grayed out, something like this:
<img width="838" alt="Screen Shot 2019-09-04 at 9 38 25 AM modified" src="https://user-images.githubusercontent.com/852673/64261862-36063380-cefb-11e9-88c6-445365dbeb22.png">

It's fine to leave the background light gray and the disabled text on the right side the same.

I'd say this is the highest priority ticket for this app right now, tied with #203.

Let me know if you have questions.  Thanks!

**Comment by jakub-bao** [comment]
@benguaraldi Fixed in v.2.0.1 and deployed for testing to `test.datim.org`
Can you verify and close?

https://test.datim.org/api/apps/User-Administration/index.html#/

**Comment by benguaraldi** [comment]
Looks great!  Thanks!
<img width="819" alt="Screen Shot 2019-09-04 at 11 49 39 AM" src="https://user-images.githubusercontent.com/852673/64270859-39ed8200-cf0a-11e9-9f1f-fc379e698e5f.png">
