### ISSUE TITLE
Cannot search by email domain  "cdc", "state.gov" etc.

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#206]
Searching by email is done by `$ilike` however, Ed Dyer is asking us to do pure `ilike` because they were used to search by domain only and also by `disabled/enabled` on triage.

@benguaraldi Can I fix this? I think it's the way the old app worked.

**Comment by benguaraldi** [comment]
@jakub-bao Yes, let's fix.  Thanks!

**Comment by jakub-bao** [comment]
Deployed yesterday to prod.
