### ISSUE TITLE
User info for malformed user crashes app

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#209]
Discovered by Ed.

![image](https://user-images.githubusercontent.com/47790868/64624866-487be380-d3b9-11e9-920f-c11578cce9e8.png)

there are some users who seem to be malformed and opening them would crash the app.

cc @benguaraldi  ~ i am about to fix this today. high priority on my list.

**Comment by jakub-bao** [comment]
for the record, this is the user account which would crash the app:
https://triage.datim.org/api/apps/User-Administration/index.html#/edit/PLqqvFbUnJl

**Comment by jakub-bao** [comment]
The user admin app expects that user is member of a single OU only. However, this user is member of level2 & level3:

![image](https://user-images.githubusercontent.com/47790868/64625866-e91ed300-d3ba-11e9-99a1-c05f825966cd.png)

**Comment by benguaraldi** [comment]
@jakub-bao That user shouldn't be that way

It'd be good if the app doesn't crash in this scenario, of course.

We can also write a script that identifies all users who have this property and change them.

**Comment by benguaraldi** [comment]
@jakub-bao It works!

This is good enough, but I'd prefer `Error` or `could not be determined` rather than `N/A`.  Could you change it?

**Comment by jakub-bao** [comment]
@benguaraldi God you. Fixed. Re-deployed to test

![image](https://user-images.githubusercontent.com/47790868/64644453-ae2f9600-d3e0-11e9-885a-10d8aae666cd.png)

**Comment by benguaraldi** [comment]
Looks good! Thanks!

Should I close, or should we wait until it's deployed?

**Comment by jakub-bao** [comment]
Deployed yesterday to prod & passing tests.
