### ISSUE TITLE
User Admin app is slow

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#217]
Reported by Josephine via slack:
> Also the user admin app is sluggish/slowish.

I think it's the same as with the Angular app. But I know how to address that.

However, I'd first start with a bit of refactor under the hood and then implement faster queries the same as the native Users app.

cc @benguaraldi

**Comment by jakub-bao** [comment]
Steps to resolve:
1. Refactor the code of the app
2. Make use of the faster endpoint which is also used by the native Users app

**Comment by benguaraldi** [comment]
@jakub-bao I recommend starting with the second step and seeing if that alone resolves it.  Does that work?

**Comment by jakub-bao** [comment]
@benguaraldi Sure. However, I'd still love to do the refactor at some point.
I'd like to make the intestines of the app more simple. So it will make my future work easier and faster.
It's an investment which would pay off in the long run.

**Comment by jakub-bao** [comment]
I've received more details on this issue from Josephine & Thomas Hancock

Thomas:
> Just in general it takes a long time to filter users.
> And then each time you add a filter as well. Can take up to a minute just to search by username, 
etc.

Most used filters:
`user type / user role / ou / email / username`

@benguaraldi If we use the DHIS2 user-dedicated endpoint we can fix filtering by `email / username`

However, filtering by `user type / user role / ou` will be more tricky.

Things to consider:
1. When searching by `user type / user role / ou` what is actually the SQL query which DHIS2 sends to our PostgreSQL server? Does the SQL have appropriate indices to make these queries fast?

@mpinardi-bao @jason-p-pickering @oodujebe @chuqyang  Do you have any experience on DATIM with debugging SQL performance?

**Comment by jakub-bao** [comment]
Reported by Josephine again via slack.
She's complaining that the operations below are slow:

1. Go to user admin and search for `OU:Tanzania` 
2. After the search add another filter and filter by `User Type:Agency`

I've tested on `triage` and I can see `#1` ~10sec & `#2` ~ 55sec

**Comment by jakub-bao** [comment]
I think I've noticed is search by usertype is done as `:ilike:Agency`... can we improve this?

**Comment by baohausian** [comment]
Filter set 01
<img width="961" alt="Screen Shot 2020-02-13 at 14 44 26" src="https://user-images.githubusercontent.com/20126962/74479817-dcc50780-4e7d-11ea-827b-1dc0b63f2dfc.png">

**Comment by benguaraldi** [comment]
Should be fixed with #265.
