### ISSUE TITLE
Group `OU xxx User Administrators` missing

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#224]
reporter per Josephine & @benguaraldi 

It seems that the new user admin app might not be granting the user administrators group in some cases when a user becomes a user admin
For instance, it appears that JknueppelSA gave the User Administrator role to nrothgerber
And nrothgerber didn't get the OU South Africa Agency HHC/CDC User Adminstrators group

**Comment by jakub-bao** [comment]
Note: Exploring if the bug appears also on Invite.

This seems to be the code which would assign `OU xxx all users`:
![image](https://user-images.githubusercontent.com/47790868/66663003-deed3000-ec17-11e9-86d3-950f8b9b264f.png)

**Comment by jakub-bao** [comment]
Nope, user invite should be fine.
The `user administrators` group is administered here:

![image](https://user-images.githubusercontent.com/47790868/66663211-44412100-ec18-11e9-9197-b733c2fcf1ba.png)

**Comment by jakub-bao** [comment]
added all code for user types. have to test all used cases.

**Comment by jakub-bao** [comment]
The new code is here... Agency/Partner has some issues we'll have to fix...

![image](https://user-images.githubusercontent.com/47790868/66677698-39968400-ec38-11e9-8526-375c17a81ac8.png)

**Comment by jakub-bao** [comment]
This is the issue to be fixed...

![image](https://user-images.githubusercontent.com/47790868/66677830-81b5a680-ec38-11e9-8ca5-4e8ffb08ac96.png)
`state.agency` is agency name
while `state.agencies.filter` is looking for IDs

**Comment by jakub-bao** [comment]
It turned out to be a bit more complex ticket because of the 6 user types and for each of them it is a different group which has to be granted. Also it depends on OU.

So I decided to write a Cypress stub method. So instead of sending the `grant UA` request all the way to the server we intercept it in the middle and inspect the request. This makes execution of the tests much faster.

Instead of waiting on 12 tests (6 user types  for grant UA and revoke UA) we will run everything faster because we don't send the requests to server but intercept.

**Comment by jakub-bao** [comment]
Cypress tests passing:

![image](https://user-images.githubusercontent.com/47790868/66853637-c483c100-ef4d-11e9-8099-7c9ec0a78883.png)

**Comment by benguaraldi** [comment]
Is this the same as #262?  If not, should this be closed as OBE?

**Comment by jakub-bao** [comment]
closing
