### ISSUE TITLE
Slow Searches: Look into putting every user into specific type groups

### ISSUE THREAD

**Issue by hardingt** [pepfar-datim/datim-user-management-ng#229]
Would it work to have groups for:
Agency Users
Partner Users
IA Users
Etc...

So instead of searching for users in a group LIKE *Agency*, we can search for users in Group "Agency Users"

I'm not sure if that would be any faster or speed up the SQL call, but might be a low tech solution to the problem.

We could test this by making an api call to an existing group and counting the SQL queries

**Comment by benguaraldi** [comment]
We're fixing the speed with #265.
