### ISSUE TITLE
Don't let admins to make edits to disabled users

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#231]
Issue reported by @hkim224 

You can go to an edit page for disabled user and make edits. However, DHIS2 won't let you save.

Let's make it obvious in the UI that you have to enable the user first.

![image](https://user-images.githubusercontent.com/47790868/67115718-d7480100-f1ac-11e9-946e-0eb37a093933.png)

https://dev.datim.org/api/apps/User-Administration/index.html#/edit/eC2Yx8XRI0R

**Comment by benguaraldi** [comment]
@jakub-bao, this appears to work in the DATIM app.  I think that we don't need to do anything here.

cc: @hkim224
