### ISSUE TITLE
Data streams active/inactive changes while inviting user

### ISSUE THREAD

**Issue by benguaraldi** [pepfar-datim/datim-user-management-ng#232]
Not a huge deal, but definitely looks weird.

Screen shot:
![67218638-b40f9280-f3f4-11e9-835e-9544d5c0c2c7](https://user-images.githubusercontent.com/852673/67237115-994f1500-f418-11e9-965e-1fbc0e549d94.png)

Before the invite was issued, I believe all radio buttons except for `ESOP: No Access` were activated.

**Comment by jakub-bao** [comment]
Fixed.

All radio buttons disabled after invite was sent...

![image](https://user-images.githubusercontent.com/47790868/71591425-3e155f00-2afa-11ea-9427-45c83105cc82.png)

will be part of the Regional MOH ticket

**Comment by jakub-bao** [comment]
@benguaraldi Can you confirm this is how this issue was supposed to be fixed?

**Comment by benguaraldi** [comment]
Looks good to me!

**Comment by jakub-bao** [comment]
@benguaraldi OK, thanks. This will be deployed as part of UA `2.0.6` here: https://github.com/pepfar-datim/Global/issues/5865

**Comment by Nazdar10** [comment]
Test: Pass
ENV: test.datim
All radio buttons disabled after invite was sent: Pass
![image](https://user-images.githubusercontent.com/50021119/72277874-c3bc0300-3600-11ea-9326-efd4d625eb0d.png)

**Comment by Nazdar10** [comment]
Smoke test: Pass
ENV: triage.testing.datim

![image](https://user-images.githubusercontent.com/50021119/72382484-5b941c80-36e7-11ea-849a-ec79d621ccb3.png)
