### ISSUE TITLE
Remove option to create Regional MOH user in Datim User Managment 

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#233]
Per @benguaraldi:

MOH (ministry of health) regional (Asia Region) users don't make any sense..

Let's remove that option... 

Right now it's possible...

![image](https://user-images.githubusercontent.com/47790868/71525374-576e9f00-289f-11ea-8d54-93febd7a4430.png)

@benguaraldi said it would be the best to show a warning message that this is not a supported combination and disable the rest of the invite page...

**Comment by jakub-bao** [comment]
@benguaraldi 

How does this look to you?

![image](https://user-images.githubusercontent.com/47790868/71590663-63ed3480-2af7-11ea-8cb5-1940de9a4682.png)

The `Invite` button is disabled.

**Comment by benguaraldi** [comment]
Looks great! Thanks!

**Comment by jakub-bao** [comment]
@benguaraldi OK, this will be tested & deployed as part of `2.0.6` UA release: https://github.com/pepfar-datim/Global/issues/5865

**Comment by Nazdar10** [comment]
Post conditions: PASS
ENV: test.datim

![image](https://user-images.githubusercontent.com/50021119/72277600-2e207380-3600-11ea-8315-4a7fc0dcef4c.png)
The Invite button is disabled.
![image](https://user-images.githubusercontent.com/50021119/72277651-47292480-3600-11ea-983d-7e695aa43693.png)

**Comment by Nazdar10** [comment]
Smoke test: Pass
ENV: triage.datim.org


![image](https://user-images.githubusercontent.com/50021119/72381743-eb38cb80-36e5-11ea-834a-4d3891c72d83.png)
