### ISSUE TITLE
Search button for ADVANCED search

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#249]
Since searching using multiple filters can be slow.
It's sometimes annoying when selecting multiple filters that the app is searching after each seletion.
Let user pick their search options and click SEARCH in the end.

**Comment by jakub-bao** [comment]
I've decided to refactor the search page. It was a bit too spaghetti code and needed to fix technical debt.
I have most of the search functionality back.

However, one thing missing, so noting it here:
Unfortunately, it's impossible to query based on userType.
The list of users has to be filtered on front-end.
Let's add that.

example:
filter by agency user type:
`filter=userGroups:ilike:agency` matches also `Global Agency xxx users`

**Comment by jakub-bao** [comment]
ok done with that. now another thing:
i've created a new simplified user model for the new search page. it will make things way easier.
must write a transform function to project from dhis2/api usermodel to the simplified one.

**Comment by jakub-bao** [comment]
Trying to wrap up determining user organization.
For partner it is obtained from user groups:

```
Determining User Group OU West Africa Region Partner 145729117 users - JSI Research And Training Institute, INC.
Determining User Group OU Nigeria Partner 850470568 all mechanisms - INSTITUTE OF HUMAN VIROLOGY
Determining User Group OU Lesotho Partner 007041168 users - Elizabeth Glaser Pediatric Aids Foundation
Determining User Group OU Kenya Partner 623392354 all mechanisms - Task Force For Global Health, Inc., The
Determining User Group OU Kenya Partner 623392354 users - Task Force For Global Health, Inc., The
```

for Agency it will be
```
Determining User Group OU Kenya Agency USAID all mechanisms
Determining User Group OU Nigeria Agency HHS/CDC all mechanisms
```

for Agency HQ it is:
```
Determining User Group Global Agency USAID users
Determining User Group Global Agency HHS/SAMHSA all mechanisms
Determining User Group Global Agency DOD all mechanisms
Determining User Group Global Agency HHS/CDC all mechanisms
Determining User Group Global Agency DOD all mechanisms
Determining User Group Global Agency USAID users
```

MOH, Inter-Agency, Global should be NA
DOD is DOD

**Comment by benguaraldi** [comment]
Closing.
