### ISSUE TITLE
Download CSV is showing through the DHIS2 app menu

### ISSUE THREAD

**Issue by benguaraldi** [pepfar-datim/datim-user-management-ng#256]
The Download CSV is showing through the DHIS2 app menu:
![Screen Shot 2020-03-17 at 4 37 48 PM](https://user-images.githubusercontent.com/852673/76899367-bb38b080-686d-11ea-890b-46f57bce1320.png)

Probably it's something to do with z-indices?

**Comment by benguaraldi** [comment]
(as reported by Thomas Hancock in Slack)

**Comment by jakub-bao** [comment]
@benguaraldi True. I went way way overboard with `z-index`. Fixed.

**Comment by benguaraldi** [comment]
Thanks, @jakub-bao!
