### ISSUE TITLE
Grant Access to this repo

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#30]
@chuqyang can you please grant me and @jakub-bao write/admin access to this repo?  We are going to start picking up where the REACT user admin app left off in this repo

FYI: @benguaraldi @Nhobby

**Comment by chuqyang** [comment]
granted.

**Comment by benguaraldi** [comment]
Also, @chuqyang, could you add the dev team to it too? Let me know if you want a separate ticket.

**Comment by chuqyang** [comment]
DATIM dev team had read permissions, I just gave them write.

**Comment by DavidNesbitt** [comment]
Thank you all!
