### ISSUE TITLE
UI: Button to navigate from invite page

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#69]
Please change the "X" button in the top right of the invite user screen to a button that says "back" (and maybe a little reverse arrow, if possible).

Current UI:
![image](https://user-images.githubusercontent.com/23367121/54387315-6ae2ad80-4671-11e9-9c9a-e94ef4d9bcea.png)

Change to something like this (but not exactly like this):
![image](https://user-images.githubusercontent.com/23367121/54387601-34f1f900-4672-11e9-848c-5c6a5a0d7cf2.png)

**Comment by jakub-bao** [comment]
Done, let's review on Wed
