### ISSUE TITLE
UI: Invite user screen - Notification when User Manager box is "checked"

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#70]
If I am on the Invite page in the REACT user admin app,

and I select the "User Manager" box,
![image](https://user-images.githubusercontent.com/23367121/54388059-44be0d00-4673-11e9-9d43-49ed84e51a7e.png)

then a notification box should appear informing the User Admin sending the invite that they are making that user a user manager, and what additional permissions (if any) are being added.

Example from Angular app version
![image](https://user-images.githubusercontent.com/23367121/54388688-ab8ff600-4674-11e9-844b-dfa02b5c13f8.png)

REACT App should say: `Adding a user manager will give this account all available user groups and access for their user type.  The following additional roles, if any, will also be assigned (based on the user type):`

**Comment by jakub-bao** [comment]
Done, let's review on Wednesday

**Comment by jakub-bao** [comment]
Note from Ben:

We need to double-check it's still true we grant user MER DOD Data View privilege.

**Comment by jakub-bao** [comment]
We're missing a message that user is getting MER Data Entry privilege (non-dod).

Note from @benguaraldi . Can we maybe improve UI to show that privilege on screen with others.

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/54710218-8fc99b80-4b1d-11e9-83da-00fc8204744b.png)

**Comment by jakub-bao** [comment]
Correct message the same as angular user management:

Because this is a user manager the following additional roles will also be assigned (based on the user type)
Data Entry MER
Data Entry MER DOD

**Comment by jakub-bao** [comment]
Also add:
 
Inter-Agency:
Because this is a user manager the following additional roles will also be assigned (based on the user type)
Data Entry SaS

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/54782347-07b6c500-4bf5-11e9-9152-c67f9a88603a.png)

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/54782376-1c935880-4bf5-11e9-9382-6d018d206f3d.png)

**Comment by jakub-bao** [comment]
@DavidNesbitt 
Hey David, look at the screenshots above.
I've added the missing user roles.

You said we might want to improve the long message. Let me know the new wording and I'll plug it in 👍

**Comment by benguaraldi** [comment]
I think we could skip the "(based on the user type)", right?

**Comment by jakub-bao** [comment]
@benguaraldi 

![image](https://user-images.githubusercontent.com/47790868/54837420-bbbf5b00-4c9c-11e9-8245-7893beccf7c1.png)
