### ISSUE TITLE
React DATIM user administration app for DOD and non-DOD (or both) partners

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#73]
Moving from ticket https://github.com/pepfar-datim/Global/issues/4673 to here:

We will go with Tim's suggested option 2:
`We completely obfuscate the difference between DoD and non DoD. The SQL view that can tell whether a given partner is DoD or not is edited from providing binary yes/no feedback to providing a third option: DoD, nonDoD, both. The app would then know which User Groups to select based on that feedback.`

We do not need to display the designation of MER, MER DoD, or both in the UI. The UI can stay as is for the MER column (and display it as MER, regardless of DoD/non-DoD access)
![image](https://user-images.githubusercontent.com/23367121/54469158-cc3a7780-476a-11e9-9e49-12c6462e45ef.png)

**Comment by benguaraldi** [comment]
Replaced with #275.
