### ISSUE TITLE
Unsaved Edit Changes notification

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#83]
Scenario:

1. User is on edit page viewing user A
2. User changes privileges B
3. User doesn't save page but clicks back button in HTML, or presses BACK button in browser, or closes browser tab with X icon
4. App should ask him to confirm exiting without saving changes

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/55346016-672b9500-547f-11e9-85c6-b01e21090fa3.png)

Done

**Comment by benguaraldi** [comment]
@jakub-bao Looks great! Could you change to:
```
You have unsaved changes. Are you sure you want to leave?
```
