### ISSUE TITLE
Filter by User Group shows too many groups

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#87]
The Angular app lets me to filter users only by **groups** I am actually **member of**:

![image](https://user-images.githubusercontent.com/47790868/55026503-7fac3300-4fd9-11e9-8f31-51794f57e7ee.png)

The React app lets me to filter users by **any group**:

![image](https://user-images.githubusercontent.com/47790868/55026557-9a7ea780-4fd9-11e9-95ac-e06e073f503a.png)

Which one is the right way?

**Comment by benguaraldi** [comment]
I think the angular app is the right way.  @DavidNesbitt, @hardingt, any opinion?

**Comment by jakub-bao** [comment]
I've filtered the groups.

Now we display only groups which user is member of:

![image](https://user-images.githubusercontent.com/47790868/54950335-6e025700-4f17-11e9-8e98-138dfdb41fb9.png)


However, now we missing "Global Users" & "Global all mechanisms".
Will add these as well.

**Comment by jakub-bao** [comment]
Resolved.

![image](https://user-images.githubusercontent.com/47790868/55009481-fab12180-4fb8-11e9-9bd3-51d189f91db4.png)

**Comment by jakub-bao** [comment]
to be reviewed by @DavidNesbitt . do we still need this restriction

**Comment by jakub-bao** [comment]
Call with @DavidNesbitt . Yes let's keep this restriction. User shouldn't be able to filter by groups they're not members of.
