### ISSUE TITLE
CSS Improvements

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#93]
- Put max-width like old app. The current app can be too wide.
- Find a better color scheme. Primary color, secondary color, headerbar color.

**Comment by jakub-bao** [comment]
Loader:

![image](https://user-images.githubusercontent.com/47790868/55015832-f8a09000-4fc3-11e9-9747-9301ac72c764.png)

**Comment by jakub-bao** [comment]
Margins

![image](https://user-images.githubusercontent.com/47790868/55015930-284f9800-4fc4-11e9-9b43-32d1a924eba1.png)

**Comment by jakub-bao** [comment]
Trying to work on colors... specially the header bar

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/55017453-23d8ae80-4fc7-11e9-8b1e-2edbd6ed1063.png)

**Comment by jakub-bao** [comment]
Happy for feedback. @DavidNesbitt @benguaraldi

**Comment by jakub-bao** [comment]
New logo added:

![image](https://user-images.githubusercontent.com/47790868/55025113-a026be00-4fd6-11e9-83db-d6a59be88eeb.png)

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/55025142-b5035180-4fd6-11e9-86a9-7f1b853d8bac.png)

**Comment by jakub-bao** [comment]
Done for now. Will need to fix layout of Invite & Edit pages. And also secondary vs. primary color for data-persist actions in later ticket.

**Comment by benguaraldi** [comment]
This looks much better!

That white guy icon, though—not sure about that!  :)  Is that from Greg's version?
